# escape=`

ARG BASE_IMAGE="python:3.12-windowsservercore-1809"
FROM ${BASE_IMAGE}

COPY docker/windows/install_vs_toolchain.ps1 C:/tmp/
SHELL ["powershell", "-Command"]
RUN C:/tmp/install_vs_toolchain.ps1; Remove-Item 'C:/tmp/install_vs_toolchain.ps1'

COPY ./conan C:/tmp/conan-recipes

ARG CESDK_VERSION=3.3.11669
ENV CONAN_USER_HOME=C:\opt\conan
SHELL ["cmd", "/S", "/C"]
RUN mkdir C:\opt\conan `
    && python -m pip install --no-cache-dir --upgrade pip wheel "conan<2.0" `
    && conan download catch2/2.13.7@ `
    && conan create -pr C:/tmp/conan-recipes/profiles/windows-v143 C:/tmp/conan-recipes/cesdk cesdk/%CESDK_VERSION%@esri-rd-zurich/stable
