# escape=`

ARG BASE_IMAGE="python:3.12-windowsservercore-1809"
FROM ${BASE_IMAGE}
SHELL ["cmd", "/S", "/C"]

ADD https://aka.ms/vs/17/release/vs_buildtools.exe C:/tmp/vs_buildtools.exe
RUN C:/tmp/vs_buildtools.exe --quiet --wait --norestart --nocache ^ `
    --installPath C:\BuildTools ^ `
    --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended ^ `
    --add Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64 ^ `
    --add Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64 ^ `
    || IF "%ERRORLEVEL%"=="3010" EXIT 0

COPY ./conan C:/tmp/conan-recipes

ARG CESDK_VERSION=3.3.11173
ENV CONAN_USER_HOME=C:\opt\conan
RUN mkdir C:\opt\conan `
    && python -m pip install --no-cache-dir --upgrade pip wheel "conan<2.0" `
    && conan download catch2/2.13.7@ `
    && conan create -pr C:/tmp/conan-recipes/profiles/windows-v143 C:/tmp/conan-recipes/cesdk cesdk/%CESDK_VERSION%@esri-rd-zurich/stable
